bugfix/fix-comments: Fix comments
userre5u/Assignments pull request #10
Opened 2023-12-28 19:31 UTC by userre5u

2023-12-30 10:37 UTC, danieldrizin requested changes

2023-12-30 10:37 UTC, danieldrizin commented on trojan/server.py
> +        cmd_func_mapping = {"lock": self.lock_screen,
מגניב ממש!

2023-12-30 10:37 UTC, danieldrizin commented on trojan/server.py
> +                client_id = prompt[7:]
מה זה ה7 הזה?

2023-12-30 10:37 UTC, danieldrizin commented on trojan/server.py
> +            elif prompt == "exit":
למה זה לא חלק מ user_func_mapping?

2023-12-30 10:37 UTC, danieldrizin commented on trojan/server.py
> +            elif prompt.startswith("select "):
ולמה גם זה לא חלק מה-mapping?

2023-12-30 10:37 UTC, danieldrizin commented on trojan/server.py
> +            conn = client[0]
it's prettier here to unwrap the tuple instead of accessing the first element
for example:
`conn, _ = client`

2023-12-30 10:37 UTC, danieldrizin commented on trojan/client.py
> +    cmd_func_mapping = {"lock": screen_lock, "download": download_file, "upload": upload_file}
האם זה המקום הנכון ליצור את המיפוי הזה?

2023-12-30 10:37 UTC, danieldrizin commented on trojan/client.py
> +        directory = data[3:]
מה זה ה3 הזה?
זאת כבר הפעם השניה שבה יש מספר מוזר בקוד (בקודמת ראיתי 7), אולי יש פה משהו שאתה עושה שרלוונטי לכל הפונקציות האלה?

2023-12-30 10:37 UTC, danieldrizin commented on trojan/client.py
> +            if "ack" == client_socket.recv(MAX_BYTES).decode(): # start sending file's data
למה צריך את ה-ack הזה?

2023-12-30 10:37 UTC, danieldrizin commented on trojan/client.py
> +    cmd_platform = {"linux": "xdg-screensaver lock", "win32": "Rundll32.exe user32.dll,LockWorkStation", "darwin": "pmset displaysleepnow"}
מגניב!

2023-12-30 10:37 UTC, danieldrizin commented on trojan/client.py
> +    cmd_platform = {"linux": "xdg-screensaver lock", "win32": "Rundll32.exe user32.dll,LockWorkStation", "darwin": "pmset displaysleepnow"}
אבל לא היית מעדיף שהדבר הזה ישב בשרת?
מה אם מחר צריך להוסיף את זה למערכת הפעלה נוספת?

2023-12-30 10:37 UTC, danieldrizin commented on trojan/server.py
> +                        file_content = fd.read(1024)
למה פה קוראים 1024 ולא MAX_BYTES?

2023-12-30 21:30 UTC, userre5u commented on trojan/server.py
> +                client_id = prompt[7:]
תוקן שמתי את הפקודה בתור פונקציה משל עצמה

2023-12-30 21:30 UTC, userre5u commented on trojan/server.py
> +            elif prompt == "exit":
בוצע

2023-12-30 21:30 UTC, userre5u commented on trojan/server.py
> +            elif prompt.startswith("select "):
גם בוצע

2023-12-30 21:31 UTC, userre5u commented on trojan/server.py
> +            conn = client[0]
בוצע

2023-12-30 21:31 UTC, userre5u commented on trojan/client.py
> +    cmd_func_mapping = {"lock": screen_lock, "download": download_file, "upload": upload_file}
צודק מצאתי לנכון לשים אותו תחת init שבשנייה שהשרת עולה

2023-12-30 21:32 UTC, userre5u commented on trojan/client.py
> +        directory = data[3:]
ה7 היה בצד שרת כדי לוודא את הclient-id תקין פה ה 3: זה התיקיה שאנחנו רוצים לעבור אלייה
תיקנתי גם את זה אין יותר sliceים

2023-12-30 21:34 UTC, userre5u commented on trojan/client.py
> +    cmd_platform = {"linux": "xdg-screensaver lock", "win32": "Rundll32.exe user32.dll,LockWorkStation", "darwin": "pmset displaysleepnow"}
תוקן, ביחד עם ניסיון ההתחרות מהלקוח לשרת אני מביא גם את הסוג מערכת הפעלה ככה שאדע איזה פקודה לשלוח ללקוח
אפשר לראות את הOS גם שעושים list אז רואים איפי פורט ומערכת הפעלה של הלקוחות שמחוברים

2023-12-30 21:34 UTC, userre5u commented on trojan/server.py
> +                        file_content = fd.read(1024)
תוקן לא שמתי לב

2023-12-30 21:37 UTC, userre5u commented on trojan/client.py
> +            if "ack" == client_socket.recv(MAX_BYTES).decode(): # start sending file's data
מכיוון שאני לא יודע האם יש לי הרשאות לעלות קובץ לנתיב מסויים (אלא אם אני מריץ ls -l) אני עלול ליפול על perm denied או על כל runtime error אחר מצד לקוח ככה אני מוודא שיש ack לפני שאני מתחיל לשלוח את מידע.

2023-12-30 21:44 UTC, userre5u commented on trojan/client.py
> +    cmd_func_mapping = {"lock": screen_lock, "download": download_file, "upload": upload_file}
תוקן שמתי בפונקציה main ואני מעביר את המילון כפרמטר לפונקציה handle_data

2024-01-06 14:42 UTC, danieldrizin approved these changes

2024-01-08 19:16 UTC, merged